print(" How to check a variable’s type?")
print("-> Chúng ta sử dụng hàm type()")
print("")
print("- In what cases, you will get SyntaxError from the compiler telling you that some of your variables have invalid names?")
print("-> Trong trường hợp tên biến trùng với tên từ khóa của VSCode, tên bắt đầu với số hoặc ký tự đặc biệt, tên phải viết liền")
print(" Can you give 3 different examples of invalid names?")
print("VD: int = 3")
print(" $s&o = 3")
print(" nam sinh = 1997")
